

name: kupidon-dev-mongo


services:

  mongo:
    build:
      dockerfile: Dockerfile
#    expose:
#      - 27017
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    extra_hosts:
      - '${MONGO_HOSTNAME}:127.0.0.1'
    volumes:
      - ./mongo/certs-dev:/data/configdb-certs/:ro
      - ./mongo/scripts:/data/configdb-scripts/:ro
      - ${MONGO_DB_DATA_PATH}/:/data/db/
#      - ../kupidon-dev-mongo-logs/:/var/log/mongodb/
#      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    entrypoint: kotlinc -script /data/configdb-scripts/mongo-start.main.kts
    environment:
      - MONGO_HOSTNAME
      - MONGO_PORT
      - MONGO_RS
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
      - MONGO_APP_DB_DATABASE
      - MONGO_APP_DB_USERNAME
      - MONGO_APP_DB_PASSWORD
    restart: unless-stopped


#  mongo-test:
#    image: mongo:7.0.21-jammy
#    entrypoint: sh -c "sleep infinity"




#volumes:
#  kupidon-mongo-data-dev:
#    external: true
#  kupidon-mongo-config-dev:
#    external: true
#  kupidon-mongo-log-dev:
#    external: true