

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
#storage:
#  dbPath: /data/db
#  journal.enabled: true



# where to write logging data.
#systemLog:
#  destination: file
#  path: /var/log/mongodb
#  logAppend: true



# network interfaces
net:
  # port will be set through cmd mongod start
  #port: 27017
  bindIp: 127.0.0.1
  bindIpAll: true


#processManagement:


# !!! Auth & keyfile will be managed by commandline args
#security:
  # authorization: disabled/enabled
  # same as if start by 'mongod --auth'
  #authorization: disabled

  # if keyfile is here then auth always will be enabled
  #keyFile: '/data/configmongo/mongoKeyFile'

#operationProfiling:

replication.replSetName: rs0

#sharding:

## Enterprise-Only Options:

#auditLog: